[book]
authors = ["Felipe S. S. Schneider"]
language = "en"
multilingual = false
src = "src"
title = "Overreact Documentation"

[output.html]
site-url = "/overreact-docs"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"
