[book]
authors = ["Felipe S. S. Schneider"]
description = "Construct precise chemical microkinetic models from first principles and solve them with numerical methods."
language = "en"
multilingual = false
src = "src"
title = "overreact documentation"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/geem-lab/overreact-guide"
mathjax-support = true
site-url = "/overreact-guide"

[output.linkcheck]

[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"
