name: Docs to PDF
on:
  push:
    branches:
      - master
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /src directory
    paths:
      - 'src/**.md'
      - 'src/**'
      
  workflow_dispatch:
    
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: src
          output_dir: pdfs
          images_dir: src/
          # for example <img src="./images/file-name.png">
          image_import: ./
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v1
        with:
          name: overreact-guide-pdf
          path: overreact-guide.pdf
